### PR TITLE
Leroy netizen/refresh token

### PR DESCRIPTION
**Pull request by leroy-netizen**
This PR addresses issue #10 
On logging in a user is assigned both an access and refresh token. When the access token expires, the user will then use the refresh token to generate a new access token

### CODE REVIEW

**Comment by leroy-netizen** [comment]
A POST request is made to the endpoint /api/auth/refresh with the refresh token as the payload. This will generate a new access and refreshToken. In future, we will be invalidating the previous access and refresh Tokens once a new one is generated.

**Comment by JESKA-JENIPHER** [comment]
This is awesome.The role being passed into the payload will also help use define user roles.Add more comments too.

**Review by JESKA-JENIPHER — APPROVED** [review]

**Review by JESKA-JENIPHER — APPROVED** [review]

**Review by JESKA-JENIPHER — APPROVED** [review]
Explain the change in status codes using comments

**Review by JESKA-JENIPHER — APPROVED** [review]

**Review by JESKA-JENIPHER — APPROVED** [review]

**Review by JESKA-JENIPHER — APPROVED** [review]

**Review by JESKA-JENIPHER — APPROVED** [review]

**Comment by leroy-netizen** [comment]
> Explain the change in status codes using comments

Definitely, I made a few changes to the status codes I was sending. I realized that I was returning a response status code of 400 for every failed request. I mean codes in the 400 range would ideally be client errors. I thought sending the exact codes for the specific requirements might be more descriptive. 409 would mean a duplicate entity (email already exists) 422 would be an unprocessable entity error if I'm not wrong. I'll have that in the comments in the next pull request I create.

**Pull request merged**
